[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:socket]
command=node /app/deploy/socket/index.cjs
directory=/app/deploy/socket
environment=NODE_ENV="production",CONFIG_PATH="/app/config"
user=%(ENV_PRAXIS_USER)s
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=1

[program:nginx]
command=nginx -c /etc/nginx/nginx.conf -g "daemon off;"
user=%(ENV_PRAXIS_USER)s
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=10

[program:nginx-logs]
command=/bin/sh /docker/log-relay.sh
user=%(ENV_PRAXIS_USER)s
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
priority=20
