/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as authLayoutRouteImport } from './pages/(auth)/layout'
import { Route as authIndexRouteImport } from './pages/(auth)/index'
import { Route as PartyGameIdRouteImport } from './pages/party/$gameId'
import { Route as ManagerConfigRouteImport } from './pages/manager/config'
import { Route as ManagerDashboardRouteImport } from './pages/manager/dashboard'
import { Route as LegacyConfigRouteImport } from './pages/legacy/config'
import { Route as ManagerQuizzLayoutRouteImport } from './pages/manager/quizz/layout'
import { Route as LegacyQuizzLayoutRouteImport } from './pages/legacy/quizz/layout'
import { Route as ManagerQuizzIndexRouteImport } from './pages/manager/quizz/index'
import { Route as LegacyQuizzIndexRouteImport } from './pages/legacy/quizz/index'
import { Route as authManagerIndexRouteImport } from './pages/(auth)/manager/index'
import { Route as authLegacyIndexRouteImport } from './pages/(auth)/legacy/index'
import { Route as PartyManagerGameIdRouteImport } from './pages/party/manager/$gameId'
import { Route as ManagerQuizzQuizzIdRouteImport } from './pages/manager/quizz/$quizzId'
import { Route as LegacyQuizzQuizzIdRouteImport } from './pages/legacy/quizz/$quizzId'

const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLayoutRoute,
} as any)
const PartyGameIdRoute = PartyGameIdRouteImport.update({
  id: '/party/$gameId',
  path: '/party/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerConfigRoute = ManagerConfigRouteImport.update({
  id: '/manager/config',
  path: '/manager/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager/dashboard',
  path: '/manager/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyConfigRoute = LegacyConfigRouteImport.update({
  id: '/legacy/config',
  path: '/legacy/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizzLayoutRoute = ManagerQuizzLayoutRouteImport.update({
  id: '/manager/quizz',
  path: '/manager/quizz',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyQuizzLayoutRoute = LegacyQuizzLayoutRouteImport.update({
  id: '/legacy/quizz',
  path: '/legacy/quizz',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizzIndexRoute = ManagerQuizzIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerQuizzLayoutRoute,
} as any)
const LegacyQuizzIndexRoute = LegacyQuizzIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyQuizzLayoutRoute,
} as any)
const authManagerIndexRoute = authManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => authLayoutRoute,
} as any)
const authLegacyIndexRoute = authLegacyIndexRouteImport.update({
  id: '/legacy/',
  path: '/legacy/',
  getParentRoute: () => authLayoutRoute,
} as any)
const PartyManagerGameIdRoute = PartyManagerGameIdRouteImport.update({
  id: '/party/manager/$gameId',
  path: '/party/manager/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerQuizzQuizzIdRoute = ManagerQuizzQuizzIdRouteImport.update({
  id: '/$quizzId',
  path: '/$quizzId',
  getParentRoute: () => ManagerQuizzLayoutRoute,
} as any)
const LegacyQuizzQuizzIdRoute = LegacyQuizzQuizzIdRouteImport.update({
  id: '/$quizzId',
  path: '/$quizzId',
  getParentRoute: () => LegacyQuizzLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/legacy/quizz': typeof LegacyQuizzLayoutRouteWithChildren
  '/manager/quizz': typeof ManagerQuizzLayoutRouteWithChildren
  '/legacy/config': typeof LegacyConfigRoute
  '/manager/config': typeof ManagerConfigRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/legacy/quizz/$quizzId': typeof LegacyQuizzQuizzIdRoute
  '/manager/quizz/$quizzId': typeof ManagerQuizzQuizzIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/legacy/': typeof authLegacyIndexRoute
  '/manager/': typeof authManagerIndexRoute
  '/legacy/quizz/': typeof LegacyQuizzIndexRoute
  '/manager/quizz/': typeof ManagerQuizzIndexRoute
}
export interface FileRoutesByTo {
  '/legacy/config': typeof LegacyConfigRoute
  '/manager/config': typeof ManagerConfigRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/': typeof authIndexRoute
  '/legacy/quizz/$quizzId': typeof LegacyQuizzQuizzIdRoute
  '/manager/quizz/$quizzId': typeof ManagerQuizzQuizzIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/legacy': typeof authLegacyIndexRoute
  '/manager': typeof authManagerIndexRoute
  '/legacy/quizz': typeof LegacyQuizzIndexRoute
  '/manager/quizz': typeof ManagerQuizzIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authLayoutRouteWithChildren
  '/legacy/quizz': typeof LegacyQuizzLayoutRouteWithChildren
  '/manager/quizz': typeof ManagerQuizzLayoutRouteWithChildren
  '/legacy/config': typeof LegacyConfigRoute
  '/manager/config': typeof ManagerConfigRoute
  '/manager/dashboard': typeof ManagerDashboardRoute
  '/party/$gameId': typeof PartyGameIdRoute
  '/(auth)/': typeof authIndexRoute
  '/legacy/quizz/$quizzId': typeof LegacyQuizzQuizzIdRoute
  '/manager/quizz/$quizzId': typeof ManagerQuizzQuizzIdRoute
  '/party/manager/$gameId': typeof PartyManagerGameIdRoute
  '/(auth)/legacy/': typeof authLegacyIndexRoute
  '/(auth)/manager/': typeof authManagerIndexRoute
  '/legacy/quizz/': typeof LegacyQuizzIndexRoute
  '/manager/quizz/': typeof ManagerQuizzIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/legacy/quizz'
    | '/manager/quizz'
    | '/legacy/config'
    | '/manager/config'
    | '/manager/dashboard'
    | '/party/$gameId'
    | '/'
    | '/legacy/quizz/$quizzId'
    | '/manager/quizz/$quizzId'
    | '/party/manager/$gameId'
    | '/legacy/'
    | '/manager/'
    | '/legacy/quizz/'
    | '/manager/quizz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/legacy/config'
    | '/manager/config'
    | '/manager/dashboard'
    | '/party/$gameId'
    | '/'
    | '/legacy/quizz/$quizzId'
    | '/manager/quizz/$quizzId'
    | '/party/manager/$gameId'
    | '/legacy'
    | '/manager'
    | '/legacy/quizz'
    | '/manager/quizz'
  id:
    | '__root__'
    | '/(auth)'
    | '/legacy/quizz'
    | '/manager/quizz'
    | '/legacy/config'
    | '/manager/config'
    | '/manager/dashboard'
    | '/party/$gameId'
    | '/(auth)/'
    | '/legacy/quizz/$quizzId'
    | '/manager/quizz/$quizzId'
    | '/party/manager/$gameId'
    | '/(auth)/legacy/'
    | '/(auth)/manager/'
    | '/legacy/quizz/'
    | '/manager/quizz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
  LegacyQuizzLayoutRoute: typeof LegacyQuizzLayoutRouteWithChildren
  ManagerQuizzLayoutRoute: typeof ManagerQuizzLayoutRouteWithChildren
  LegacyConfigRoute: typeof LegacyConfigRoute
  ManagerConfigRoute: typeof ManagerConfigRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  PartyGameIdRoute: typeof PartyGameIdRoute
  PartyManagerGameIdRoute: typeof PartyManagerGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/party/$gameId': {
      id: '/party/$gameId'
      path: '/party/$gameId'
      fullPath: '/party/$gameId'
      preLoaderRoute: typeof PartyGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/config': {
      id: '/manager/config'
      path: '/manager/config'
      fullPath: '/manager/config'
      preLoaderRoute: typeof ManagerConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/dashboard': {
      id: '/manager/dashboard'
      path: '/manager/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/config': {
      id: '/legacy/config'
      path: '/legacy/config'
      fullPath: '/legacy/config'
      preLoaderRoute: typeof LegacyConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quizz': {
      id: '/manager/quizz'
      path: '/manager/quizz'
      fullPath: '/manager/quizz'
      preLoaderRoute: typeof ManagerQuizzLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/quizz': {
      id: '/legacy/quizz'
      path: '/legacy/quizz'
      fullPath: '/legacy/quizz'
      preLoaderRoute: typeof LegacyQuizzLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quizz/': {
      id: '/manager/quizz/'
      path: '/'
      fullPath: '/manager/quizz/'
      preLoaderRoute: typeof ManagerQuizzIndexRouteImport
      parentRoute: typeof ManagerQuizzLayoutRoute
    }
    '/legacy/quizz/': {
      id: '/legacy/quizz/'
      path: '/'
      fullPath: '/legacy/quizz/'
      preLoaderRoute: typeof LegacyQuizzIndexRouteImport
      parentRoute: typeof LegacyQuizzLayoutRoute
    }
    '/(auth)/manager/': {
      id: '/(auth)/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof authManagerIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/legacy/': {
      id: '/(auth)/legacy/'
      path: '/legacy'
      fullPath: '/legacy/'
      preLoaderRoute: typeof authLegacyIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/party/manager/$gameId': {
      id: '/party/manager/$gameId'
      path: '/party/manager/$gameId'
      fullPath: '/party/manager/$gameId'
      preLoaderRoute: typeof PartyManagerGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/quizz/$quizzId': {
      id: '/manager/quizz/$quizzId'
      path: '/$quizzId'
      fullPath: '/manager/quizz/$quizzId'
      preLoaderRoute: typeof ManagerQuizzQuizzIdRouteImport
      parentRoute: typeof ManagerQuizzLayoutRoute
    }
    '/legacy/quizz/$quizzId': {
      id: '/legacy/quizz/$quizzId'
      path: '/$quizzId'
      fullPath: '/legacy/quizz/$quizzId'
      preLoaderRoute: typeof LegacyQuizzQuizzIdRouteImport
      parentRoute: typeof LegacyQuizzLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authIndexRoute: typeof authIndexRoute
  authLegacyIndexRoute: typeof authLegacyIndexRoute
  authManagerIndexRoute: typeof authManagerIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authIndexRoute: authIndexRoute,
  authLegacyIndexRoute: authLegacyIndexRoute,
  authManagerIndexRoute: authManagerIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface LegacyQuizzLayoutRouteChildren {
  LegacyQuizzQuizzIdRoute: typeof LegacyQuizzQuizzIdRoute
  LegacyQuizzIndexRoute: typeof LegacyQuizzIndexRoute
}

const LegacyQuizzLayoutRouteChildren: LegacyQuizzLayoutRouteChildren = {
  LegacyQuizzQuizzIdRoute: LegacyQuizzQuizzIdRoute,
  LegacyQuizzIndexRoute: LegacyQuizzIndexRoute,
}

const LegacyQuizzLayoutRouteWithChildren =
  LegacyQuizzLayoutRoute._addFileChildren(LegacyQuizzLayoutRouteChildren)

interface ManagerQuizzLayoutRouteChildren {
  ManagerQuizzQuizzIdRoute: typeof ManagerQuizzQuizzIdRoute
  ManagerQuizzIndexRoute: typeof ManagerQuizzIndexRoute
}

const ManagerQuizzLayoutRouteChildren: ManagerQuizzLayoutRouteChildren = {
  ManagerQuizzQuizzIdRoute: ManagerQuizzQuizzIdRoute,
  ManagerQuizzIndexRoute: ManagerQuizzIndexRoute,
}

const ManagerQuizzLayoutRouteWithChildren =
  ManagerQuizzLayoutRoute._addFileChildren(ManagerQuizzLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
  LegacyQuizzLayoutRoute: LegacyQuizzLayoutRouteWithChildren,
  ManagerQuizzLayoutRoute: ManagerQuizzLayoutRouteWithChildren,
  LegacyConfigRoute: LegacyConfigRoute,
  ManagerConfigRoute: ManagerConfigRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  PartyGameIdRoute: PartyGameIdRoute,
  PartyManagerGameIdRoute: PartyManagerGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
